spring:
  # h2.console.enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate.ddl-auto: validate
    defer-datasource-initialization: false
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: bookadmin
    password: password
  flyway:
    user: bookadmin
    password: password
    locations: classpath:db/migration/common,classpath:db/migration/{vendor}
  profiles:
    # H2 DB by default
    active: default

logging.level:
  org:
    # Show bind values
    hibernate.type.descriptor.sql: trace
